"""empty message

Revision ID: d8efb96904f2
Revises: 0005_matches
Create Date: 2026-05-31 18:52:11.983640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8efb96904f2'
down_revision: Union[str, None] = '0005_matches'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_paddle_events_event_id', 'paddle_events', type_='unique')
    op.drop_index('ix_paddle_events_event_id', table_name='paddle_events')
    op.create_index(op.f('ix_paddle_events_event_id'), 'paddle_events', ['event_id'], unique=True)
    op.drop_constraint('uq_purchases_paddle_txn', 'purchases', type_='unique')
    op.drop_index('ix_purchases_paddle_transaction_id', table_name='purchases')
    op.create_index(op.f('ix_purchases_paddle_transaction_id'), 'purchases', ['paddle_transaction_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchases_paddle_transaction_id'), table_name='purchases')
    op.create_index('ix_purchases_paddle_transaction_id', 'purchases', ['paddle_transaction_id'], unique=False)
    op.create_unique_constraint('uq_purchases_paddle_txn', 'purchases', ['paddle_transaction_id'])
    op.drop_index(op.f('ix_paddle_events_event_id'), table_name='paddle_events')
    op.create_index('ix_paddle_events_event_id', 'paddle_events', ['event_id'], unique=False)
    op.create_unique_constraint('uq_paddle_events_event_id', 'paddle_events', ['event_id'])
    # ### end Alembic commands ###
